### ISSUE TITLE
IronList causes the browser to freeze on scrolling

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-iron-list-flow#107]
IronList causes the browser to freeze on scrolling.

Vaadin 14.2.0, IronList flow 2.0.0.jar.

Not setting the placeholder item will cause the browser to freeze immediately, but even when I set the placeholder item, the bug can be reproduced rather easily.

I'm attaching a screencast to demonstrate the issue.
[Screencast from 09.06.2020 11.08.22.webm.zip](https://github.com/vaadin/vaadin-iron-list-flow/files/4750796/Screencast.from.09.06.2020.11.08.22.webm.zip)

When IronList is replaced by a single-column Grid, the performance is smooth, so it's definitely not a problem of using ComponentRenderer.

**Comment by mvysny** [comment]
Example project:
[beverage-buddy-vok.zip](https://github.com/vaadin/vaadin-iron-list-flow/files/4750803/beverage-buddy-vok.zip)

1. Unzip the example app and open it in Intellij IDEA
2. Run the app in Tomcat
3. Navigate to http://localhost:8080/ - the Review List is opened. Scroll the list of reviews a bit - eventually the list disappears and the browser freezes.

**Comment by mvysny** [comment]
Maybe it would be possible to replicate the freeze with in-memory data - just let me know and I'll prepare such a project.

**Comment by tomivirkki** [comment]
If this issue isn't specific to Gradle/Kotlin/IntellliJ, please provide an IDE-agnostic repro in Java/Maven.

**Comment by mvysny** [comment]
The issue is not specific to Gradle/Kotlin and so the language of the project should not matter.

Here's a Java/Maven example app. Just scroll the iron list couple of times.
[skeleton-starter-flow.zip](https://github.com/vaadin/vaadin-iron-list-flow/files/4779903/skeleton-starter-flow.zip)

**Comment by tomivirkki** [comment]
Thanks, I tried the new project and was able to reproduce the issue just by scrolling the list.

Bumping iron-list version from 3.0.2 to 3.1.0 seems to resolve the issue, however. Can you verify? In that case https://github.com/vaadin/vaadin-iron-list-flow/pull/104 could be enough to fix this.

**Comment by mvysny** [comment]
How can I do that please? I've added a Maven dep:
```xml
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-iron-list-flow</artifactId>
            <version>3.1.0</version>
        </dependency>
```
but the `IronList` class references `@NpmPackage(value = "@polymer/iron-list", version = "3.0.2")`. I've tried to overwrite the version in `package.json` but it gets overwritten when Vaadin starts.

**Comment by mvysny** [comment]
I somehow managed to v-bump iron list with a magic combination of
```
@NpmPackage(value = "@polymer/iron-list", version = "3.1.0")
public class MyIronList<T> extends IronList<T> {
}
```
and overwriting the version in package.json and deleting package-lock.json. I can verify that v-bump to 3.1.0 fixes the issue and I'm unable to reproduce the issue anymore.

**Comment by tomivirkki** [comment]
Closed by https://github.com/vaadin/vaadin-iron-list-flow/pull/104 and https://github.com/vaadin/vaadin-iron-list-flow/pull/109
