### ISSUE TITLE
Basic Iron List shows nothing

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-iron-list-flow#18]
```
IronList<String> ironList = new IronList<>();
ironList.setHeight("50px");
Stream<String> items = IntStream.range(0, 100)
	.mapToObj(i -> ("Item " + i));
ironList.setItems(items);
```

Expected:
An iron list showing some rows with "Item X" text

Actual:
A 0px wide iron list

**Comment by pleku** [comment]
Which type of layout is the `IronList` added to?

Looks like we have lots of components that would need a default size to work always in any DOM structure or some default theming is missing.

**Comment by Artur-** [comment]
VerticalLayout, see https://github.com/vaadin/platform/blob/master/vaadin-platform-test/src/main/java/com/vaadin/platform/test/ComponentsView.java
