### ISSUE TITLE
Root path binding might break the app

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-iron-list-flow#31]
What's the reason to have `@Route("")` here? Other flow components do not have such binding.
What if there is `vaadin-iron-list-flow` as a dependency and another view registered to the root path?

**Comment by Legioth** [comment]
What class are you referring to? The only classes I can find with a `@Route` annotation in this repository are the demo views that are only included in the `test` scope.

**Comment by alexberazouski** [comment]
Exactly those. I have this dependency with `<classifier>demo</classifier>`
