### ISSUE TITLE
Can't use as Composite<IronList>

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-iron-list-flow#40]
Using the component as generic type of `Composite` results in this exception:

```
java.lang.IllegalStateException: Neither class 'MyList' nor its super classes declare
event handler method 'setRequestedRange'
```

Use case:

```java
abstract ListLayout<T, L extends Component & HasDataProvider<T>> extends Composite<L> {}

class MyList extends ListLayout<Person, IronList<Person>> {}
```

**Comment by Legioth** [comment]
I think this is a generic Flow issue related to finding `$server` methods from composite content classes.

**Comment by Legioth** [comment]
Issue moved to [vaadin/flow #4198](https://github.com/vaadin/flow/issues/4198) via [**ZenHub**](https://www.zenhub.com/)
