### ISSUE TITLE
Item not shown after first time iron list visible

### ISSUE THREAD

**Issue by steffen-harbich-itc** [vaadin/vaadin-iron-list-flow#52]
When I have an IronList that initially is invisible, later - e.g. on button click - made visible and filled with items, then it is not shown. Example code:

```
        IronList<String> testList = new IronList<>();
        testList.setVisible(false);
        add(testList);

        Button button = new Button("Click me", event -> {
            testList.setVisible(true);
            testList.setItems("Item 1", "Item 2");
        });
        add(button);
```
However, when I add another item (e.g. again in a button click) then it is shown as expected. Unfortunately, I cannot provide a simple example project (see issue #51).

**Comment by denis-anisimov** [comment]
This should be already fixed actually.
Try to use latest release.
