### ISSUE TITLE
IronList placeholder item support

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-iron-list-flow#6]
@Legioth commented on [Wed Nov 15 2017](https://github.com/vaadin/flow/issues/2924)

By default, the `<template>` tag populated by the `IronList` component will use something like a `<dom-if>` to only use the component's `Renderer` for items that have already been lazy loaded. For missing items, an empty inline element is used instead.

It should also be possible for the user to define a placeholder item (`void setPlaceholderItem(T placeholderItem)` and a corresponding getter). For a non-`null` placeholder item, the conditional part in the `<template>` is skipped and the values from the item are instead used with the regular `Renderer`.

### Acceptance Criteria
- There is an example that shows the usage of placeholder item to show just the property names or "-", "..." or whatever for the data

**Comment by gilberto-torrezan** [comment]
The idea of the placeholder item works great for regular templates, but it has a problem with `ComponentTemplateRenderer`s : the same component instance cannot be reused across multiple placeholders.

One way of supporting this is to stringfy the rendered component and set it as a template for the placeholders, but that removes the possibility of making the component dynamic (ie.: it can't be changed after the template is set).

**Comment by Legioth** [comment]
I think the conclusion in some offline discussion was that it's a good compromise that the rendered placeholders with a component renderer would not be dynamic.

**Comment by gilberto-torrezan** [comment]
It was implemented that way.
