### ISSUE TITLE
OSGi: ERROR: bundle com.vaadin.flow.component.ironlist:1.2.1 (92)Component descriptor entry 'OSGI-INF/com.vaadin.flow.component.ironlist.osgi.IronListContributor.xml' not found

### ISSUE THREAD

**Issue by enver-haase** [vaadin/vaadin-iron-list-flow#67]
Start up the

base-starter-flow-osgi and find

ERROR: bundle com.vaadin.flow.component.ironlist:1.2.1 (92)Component descriptor entry 'OSGI-INF/com.vaadin.flow.component.ironlist.osgi.IronListContributor.xml' not found

in the log on screen.

**Comment by pleku** [comment]
Fixed with https://github.com/vaadin/flow-component-base/issues/116 since 12.0.3
