### ISSUE TITLE
Sorting list items

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-iron-list-flow#88]
`IronList` should provide an API to set the sort orders that will be used to query the data provider.

**Comment by heruan** [comment]
Found: `getDataCommunicator().setBackEndSorting(...)`!

**Comment by Legioth** [comment]
There's also another way that doesn't involve any component API at all. You can wrap an existing `DataProvider` instance using `withConfigurableFilter()`. You can then configure the wrapper to use any filter and pass that filter to the component.

**Comment by heruan** [comment]
I already do this for *filtering*, but I couldn't find a method to set *sorting* on the wrapper.

**Comment by Legioth** [comment]
Oh. Small reading comprehension mistake on my behalf. You're absolutely right.

**Comment by heruan** [comment]
Maybe wrapper for sorting would be useful too?
